### ISSUE TITLE
PyCloud 0.9.12 missing cloudy_dict to enable useof Cloudy23.03 output

### ISSUE THREAD

**Issue by kaya4me2** [Morisset/pyCloudy#12]
Attempting to use PyCloud with C23.01 Cloudy release. 

Code fails in cell with 

Mod = pc.CloudyModel(full_model_name)

error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-100-b068d25a318a> in <module>
      1 # Reading the Cloudy outputs in the Mod CloudyModel object
----> 2 Mod = pc.CloudyModel(full_model_name)

/opt/anaconda3/envs/pycloudy/lib/python3.7/site-packages/pyCloudy/c1d/cloudy_model.py in __init__(self, model_name, verbose, read_all_ext, read_rad, read_phy, read_emis, read_grains, read_cont, read_heatcool, read_lin, read_opd, read_pressure, read_abunds, list_elem, distance, line_is_log, emis_is_log, ionic_str_key)
    139                 self._init_lin()
    140             if read_emis:
--> 141                 self._init_emis()
    142             if read_cont:
    143                 self._init_cont()

/opt/anaconda3/envs/pycloudy/lib/python3.7/site-packages/pyCloudy/c1d/cloudy_model.py in _init_emis(self)
    333             self.emis_labels = np.asarray(emis.dtype.names[1::])
    334 
--> 335             if self.cloudy_version_major > 13:
    336                 # We are with c17+ and will create emis_labels_13
    337                 self.emis_labels_17 = self.emis_labels

TypeError: '>' not supported between instances of 'str' and 'int'

I think what is missing in the utils/Config.py is the addition for the newest version of Cloudy23.01 to whit a change of the order 

cloudy_dict = {'10.00': '/usr/local/Cloudy/c10.00/cloudy.exe',
                    '13.03': '/usr/local/Cloudy/c13.03/source/cloudy.exe',
                    '17.00': '/usr/local/Cloudy/c17.00/source/cloudy.exe',
                    '17.01': '/usr/local/Cloudy/c17.01/source/cloudy.exe',
                    '17.02': '/usr/local/Cloudy/c17.02/source/cloudy.exe',
                    '17.03': '/usr/local/Cloudy/c17.03/source/cloudy.exe',
                    '23.01': '/usr/local/Cloudy/c23.01/source/cloudy.exe'}

**Comment by pentyum** [comment]
Upgrade to the newest version of pyCloudy on Github.

**Comment by Morisset** [comment]
This issue has been solver in a previous commit.
