### ISSUE TITLE
pyCloudy fails to get the version on C23.01

### ISSUE THREAD

**Issue by andresgur** [Morisset/pyCloudy#13]
Most recent Cloudy version prints the version number in the .out files as
"Cloudy (c23.01)"
as opposed to previous versions, e.g.
"Cloudy 17.03" or "Cloudy 22.02"
thus line 556 of cloudy_model.py
`self.cloudy_version_major = pc.sextract(self.cloudy_version,'Cloudy ','.')`
returns
"(c23"
which cannot be parsed as int in line 562 of cloudy_model.py
`if int(self.cloudy_version_major) >= 17:`

**Comment by Morisset** [comment]
Hi,
The version I have for Cloudy 23.01 prints out "Cloudy 23.01" in the first line of the output file. and pyCloudy manages it successfully.
We also find a better way to deal with Cloudy major version, this has been included in a recent update of pyCloudy (0.9.13). Did you tried with this last version?
Ch.

**Comment by andresgur** [comment]
Hi Morriset,
I installed the last version of Cloudy using `git clone https://gitlab.nublado.org/cloudy/cloudy.git -b c23.01 c23.01` and I also tried `git clone https://gitlab.nublado.org/cloudy/cloudy.git` and both printed the version as I stated above... not sure whether I did not get the latest version or perhaps I got the developer one?

Yes I was using the latest pycloudy version, so the problem is really on how cloudy is printing the version. 
Thanks

**Comment by Morisset** [comment]
Quite puzzling! I just downloaded the version 23.01 using `curl -k -O https://data.nublado.org/cloudy_releases/c23/c23.01.tar.gz`, compiled it in the source directory and run:
./cloudy.exe -e test
The output starts with:

                                                          Cloudy 23.01
                                                         www.nublado.org

                                                  PRNG seed: 0x5c1cd2f35de9a3d5
I then tried with the git clone and the first line in this case changed to  Cloudy (c23.01)!!!
The best would be to use the released version, and not the developer one.
Best regards,
Christophe

**Comment by Morisset** [comment]
Cloudy development team updated the code on the branch so that the issue should not be present anymore. Thanks a lot for pointing this out.
Best regards,
Christophe
