### ISSUE TITLE
The computed ionization fractions 

### ISSUE THREAD

**Issue by tekkamanmaverick** [Morisset/pyCloudy#6]
Hi Christophe,

Could you tell me how to compute the ionization fractions by pycloudy?
I want to plot the PIE abundance of Carbon species as a function of temperature.

Thank you.

**Comment by Morisset** [comment]
Hi,
This place is more related with issue of the pyCloudy code. In case of any demand related to help, it is better to ask for an account on the discussion group and ask there: https://groups.google.com/g/pycloudy
Christophe
