### ISSUE TITLE
pyCloudy vs Cloudy17.03 deprecation of comment lines and need for hden in options

### ISSUE THREAD

**Issue by kaya4me2** [Morisset/pyCloudy#8]
Seems like the new release of Cloudy17.03 has a few "bug" features that make the example notebooks fail to execute.

Bug#1:

In Cloudy17.03 the comment character // is deprecated and if used in model_1.in throws an error. One need to go in and
manually edit the model_1.in file created in the notebook https://sites.google.com/site/pycloudy/examples/example-1 and place in the proper comment character in cols1 and 2: ## 

Notebook model_1. in file throws warning error:
NOTE: one of these comment characters was found in the input: //, %, *, or ;.
 Using these is deprecated and they will be removed in the next major release.
 Please convert your input deck using scripts/ccc.pl.

Fix is to manually edit the model_1.in to whit:

Proper syntax:
## /////////////////////////////////
title model_1
## /////////////////////////////////
set punch prefix "model_1"

Bug#2
Defining some of the model parameters as illustrated in the notebook fail has the KEYWORD dens not properly passed in C17.03

# Define some parameters of the model:
model_name = 'model_1'
full_model_name = '{0}{1}'.format(dir_, model_name)
dens = 2. #log cm-3
Teff = 45000. #K
qH = 47. #s-1
r_min = 5e17 #cm
dist = 1.26 #kpc
 
To get around this bug (dens = 2), one needs to ADD into the options cell (last line)
            'print line optical depth', 'hden = 2.0'

With this definition the hydrogen density is now defined wit the proper KEYWORD and Cloudy17.03 will execute properly and run the model producing all the results in the rest of the notebook.

**_So does pyCloudy need a few updates for compatibility with Cloudy17.03_**

System / Package Versions

numpy == 1.20.2
pyCloudy == 0.9.10
os == Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

**Comment by kaya4me2** [comment]
proper syntax use be ##

in lead columns (sorry)

**Comment by Morisset** [comment]
Hi!
You're right. I think it is time to make this release from the devel version I have on the github since more than 1 year and which correct this in advance.
I will publish the 0.9.11 version that solve these problemes ASAP.
Thanks for the feedback, enjoy nebulae !
Christophe
